---
title: "Assignment-1 : R Examples"
author: "Leyla Yiğit"
date: "16 Ekim 2018"
output: html_document
---


## Find Three R Examples about My Work
I have been working “Information Management Consultant” for almost five years.  Now working at Kafein Software Consultancy for “KVKK Data Management and Achieving Project” development at Vodafone. My task descritions are all about data. All data source, data warehouses include big data, firstly should be scanned in order to find sensitive personal data and this sensitive data is either masked, deleted or other necessary actions are take. So as to decide which data is sensitive without achieving data detail because of security precautions at Vodafone, is really challenging job. In the process of analyzing and deciding PII (Personally Identifiable Information) data R can be used. At my previous work, Halk Bank APKO Data visualization project.  Tableau, data visualization and analysis tool, was used. This tool is really successful because of working an integrated way R and Python codes. Business sides of project demanded challenging tasks necessities using R and Python integration. By using R, Python and SQL codes, Tableau is even able to create 3D dynamics cubes or graphics.  I could not succeed to finish these tasks and decided to have a master degree to learn this knowhow. In order to be a successful data scientist I must learn R and Python and the other data science skills. My aim is to work a position requires heavily data analytics, data visualization integrated with Python and R, data coding like Shell, PostgreSQL. I like to challenge big and complex data and get meaningful results from it.

## RStudio Conference
The RStudio Conference is about Catlin Seaview Survey project named “Automated Visualizations for Big Data” mainly posits that effective visualization in a method for extracting, summarizing and visualizing the big and complex data with Rmarkdown, dplyr and ggplot2 is possible and gives valuable results. By the help of Rmarkdown, reports are able to produce from one source script .Parameters are inserted construction document so that unique reports creation is possible easily. By using an automated reporting system, big data can be handled even in this project images has a high number. Many reproducible reports, extracting, summarizing, consistent data exploratory and visualizing data at multiple spatial scales is possible in a short time in Rmarkdown; error stems from people is diminished and there is more time to decision making and analyzing. 
+ [Link1](https://www.youtube.com/watch?v=ZudrjJz8OA0)

## Example 1:
For Efficient data visualization, answering all questions about business, the data scientist should firstly cover data analysis. The meaningful results should be given business part not all data or just numbers instead of statistical outputs. This video is about data analysis with R, advantages of R, R ability for data visualization. R is a great language for exploring data.
+ [Link2](https://www.youtube.com/watch?v=Ve2lff1naXQ)

## Example 2:
Second process about data visualization with R is , R package usage .The post is about using R and Tableau for data visualization. R enhances Tableau capabilities from these perspectives: statistical analysis on data. In this example Geocoding in visualization is mentioned. Tableau has also geocoding calculation methods but without R and R libraries it is difficult. Geocoding map contains the input addresses and their location according to the calculated geolocation coordinate. Using the R package ggmaps we can easily generate the geolocation coordinates.
+ [Link3](https://towardsdatascience.com/geocoding-tableau-and-r-integration-c5b32dc0eda6)

## Example 3:
After analysis and calculations, dishoarding worksheets is the final phase. This post writer mentions how to use shinydashboard package of R and creating a dashboard by using this package. Dashboards created by Tableau need more human interaction, yet in this post human interaction is less. R offers superb analytical ability and flexibility. If you are working in Finance sector, priories can change any time therefore developer need to see all analysis and calculations in one place, changes should be done easily. 
+ [Link4](https://www.r-bloggers.com/introducing-the-new-zealand-trade-intelligence-dashboard/)




