---
title: "311802034_Leyla_Yiğit_STAT_Final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#INSTALL PACKAGES AND LIBRARIES
#install.packages("GGally")
#install.packages("ggpubr")

library(readxl)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)
library(rsconnect)
library(plotly)
library(gapminder)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(readxl)
library(GGally)
library(ggpubr)
library(readxl)
```


```{r SET WD}
#SET LOCAL  PLACE OF EXCELS
#CREATE DATA FRAME TO STORE DATA 

setwd("C:\\Users\\Kafein\\Desktop\\STUDY\\MEF\\ISTATISTIK\\FINAL") # set local place of excel data

df <- data.frame(matrix(ncol = 6, nrow = 0)) #define a data frame
names <- c("x1", "x2", "x3", "x4", "x5", "y") #col_names for raw_data
colnames(df) <- names

data_final <- data.frame(matrix(ncol = 6, nrow = 0))
names <- c("x1", "x2", "x3", "x4", "x5", "y")
colnames(data_final) <- names


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

#A LOOP is used for to get avarage colums of tickness,duration,valtage,temparature,Ingress that compose DNSSM
setwd("C:\\Users\\Kafein\\Desktop\\STUDY\\MEF\\ISTATISTIK\\FINAL") 
files <- list.files(pattern=".xlsx")
files <- str_remove_all(files, "~$")
for(i in 1:length(files))
{
  print(i)
  filename <-files[i]
  data <-read_excel(filename,sheet="Record_CMC")
  data <- data %>% slice(17:51)  
  data <- data[,c(4:6)]
  for (l in c(1,2,3))
  {
    j <- 1
    print(l)
    for (k in c(3,12,15,19,28,33)) 
    {
      print(k) 
      cols = k;
      df[which(1==1),j]<-c(data[cols,l])
      j <- j + 1
    } 
    data_final <- rbind(data_final, df)
  }
  assign(x = filename,value = data)
}
```

```{r pressure, echo=FALSE}
#ckeck data
data_final <- data_final %>% select(y,x1,x2,x3,x4,x5)

#give data table a logical name
Dnssm_Anaylsis_Data<-readRDS("data.rds")
#change column names
colnames(Dnssm_Anaylsis_Data) <- c("Thickness","Duration","Voltage","Temperature","Ingress","Dnssm") 
#ckeck data again
Dnssm_Anaylsis_Data <- Dnssm_Anaylsis_Data %>% select("Thickness","Duration","Voltage","Temperature","Ingress", "Dnssm")


str(Dnssm_Anaylsis_Data)
```
