DROP TABLE TRFM.CUSTOMER_IDENTIFICATION_TMP10 CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE TRFM.CUSTOMER_IDENTIFICATION_TMP10
(
  URUN_TIPI            VARCHAR2(4 BYTE),
  MUS_NO               NUMBER,
  ILK_ISLEM_TARIHI170  DATE
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


GRANT INSERT, SELECT ON TRFM.CUSTOMER_IDENTIFICATION_TMP10 TO ETL;

GRANT SELECT ON TRFM.CUSTOMER_IDENTIFICATION_TMP10 TO R_OFSDATA;
