GRANT SELECT,UPDATE,DELETE,INSERT  ON  DM_MIS.DIM_MIS_BOLGE  TO ETL;
  GRANT SELECT ON DM_MIS.DIM_MIS_BOLGE  TO PRSN; 
GRANT SELECT ON DM_MIS.DIM_MIS_BOLGE TO OFSDATA,R_OFSDATA;




GRANT SELECT ON  EXTR.FS_FINANCIAL_DATA_RAW  TO PRSN;

GRANT SELECT ON EXTR.FS_USERID_VIEW TO PRSN;

GRANT SELECT ON EXTR.FS_GOREV TO PRSN;

GRANT SELECT ON EXTR.FS_SUBE TO PRSN; 

GRANT SELECT ON EXTR.FS_IL  TO PRSN; 

GRANT SELECT ON EXTR.FS_SPR_REF  TO PRSN; 
GRANT SELECT ON EXTR.FS_CORP_BILANCO_RAW  TO PRSN; 

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_FINANCIAL_DATA_RAW  TO ETL;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_USERID_VIEW  TO ETL;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_GOREV TO ETL;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_SUBE TO ETL;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_IL TO ETL;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_SPR_REF  TO ETL;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  EXTR.FS_CORP_BILANCO_RAW  TO ETL;

GRANT SELECT ON EXTR.FS_FINANCIAL_DATA_RAW TO OFSDATA,R_OFSDATA;

GRANT SELECT ON  EXTR.FS_USERID_VIEW   TO OFSDATA,R_OFSDATA;

GRANT SELECT ON EXTR.FS_GOREV  TO OFSDATA,R_OFSDATA;

GRANT SELECT ON EXTR.FS_SUBE  TO OFSDATA,R_OFSDATA;

GRANT SELECT ON EXTR.FS_IL  TO OFSDATA,R_OFSDATA;

GRANT SELECT ON EXTR.FS_SPR_REF TO OFSDATA,R_OFSDATA;

GRANT SELECT ON EXTR.FS_CORP_BILANCO_RAW  TO OFSDATA,R_OFSDATA;




GRANT SELECT ON PRSN.FINDATA_ENTER_COUNT  TO OFSDATA,R_OFSDATA;

GRANT SELECT,UPDATE,DELETE,INSERT  ON PRSN.FINDATA_ENTER_COUNT  TO ETL;




GRANT SELECT ON TRFM.TEMP_LOG_CAT  TO OFSDATA,R_OFSDATA;

GRANT SELECT,UPDATE,DELETE,INSERT  ON TRFM.TEMP_LOG_CAT TO ETL;


PRSN.TIME_SPEND_SECOND 



GRANT SELECT ON PRSN.TIME_SPEND_SECOND  TO OFSDATA,R_OFSDATA;

GRANT SELECT,UPDATE,DELETE,INSERT  ON  PRSN.TIME_SPEND_SECOND  TO ETL;


GRANT SELECT ON PRSN.TIME_SPEND_SECOND_SUMMARY TO OFSDATA,R_OFSDATA;

GRANT SELECT,UPDATE,DELETE,INSERT  ON PRSN.TIME_SPEND_SECOND_SUMMARY TO ETL;


GRANT SELECT ON PRSN.PROPOSAL_DETAIL   TO OFSDATA,R_OFSDATA;

GRANT SELECT,UPDATE,DELETE,INSERT  ON PRSN.PROPOSAL_DETAIL   TO ETL;